### ISSUE TITLE
Always just one offer for operation "ItemLookup"

### ISSUE THREAD

**Issue by beatschubser** [dmcquay/node-apac#53]
I can't seem to get more than one offer using the operation ItemLookup like shown below:

opHelper.execute('ItemLookup', {
	  'ItemId': 'B00NJGRLUY'
	, 'Operation': 'ItemLookup'
	, 'ResponseGroup': 'Offers'
}

I can see <TotalNew>50</TotalNew> in the response, but only one <Offer>-Tag within <Offers>.

Any idea?

**Comment by dmcquay** [comment]
I'm not sure I understand. I would assume there is only one offer associated with that item. Looking up this item on amazon.com, that looks right.

http://www.amazon.com/Samsung-Chromebook-Laptop-Celeron-Silver/dp/B00NJGRLUY/ref=sr_1_1?ie=UTF8&qid=1459659201&sr=8-1&keywords=B00NJGRLUY

Not sure what you mean by "I can see 50 in the response, but only one -Tag within."

Since this is a pretty old issue I'm going to close this and ask that you re-open if I have not resolved your issue and if you actually still care.
