### ISSUE TITLE
endPoint cannot be changed after initial execute

### ISSUE THREAD

**Issue by beatschubser** [dmcquay/node-apac#54]
When the endPoint gets changed after the plugin has already been executed, it will generate an invalid request.

As a quick fix I commented out the following condition in OperationHelper.prototype.getSignatureHelper:

if (typeof(this.signatureHelper) === 'undefined')

**Comment by fwevans** [comment]
I believe I am having this problem as well. Did you discover this because the endPoint should be webservices.amazon.com rather than ecs.amazonaws.com? http://docs.aws.amazon.com/AWSECommerceService/latest/DG/AnatomyOfaRESTRequest.html#EndpointsandWebServices

Might be a good idea to change the default as well unless there is some other reason to use ecs.amazonaws.com...

**Comment by trentmillar** [comment]
fyi- I just noticed this issue, looked at the code and think it will affect me too. I've forked and may send a pr shortly.

**Comment by dmcquay** [comment]
Please see the discussion on @trentmillar's PR if you are interested.

**Comment by dmcquay** [comment]
Link to said PR: https://github.com/dmcquay/node-apac/pull/58

**Comment by dmcquay** [comment]
Closing this due to lack of interest. Please feel free to reopen.
