### ISSUE TITLE
npm run build throws an error with create react app

### ISSUE THREAD

**Issue by rokit** [dmcquay/node-apac#90]
Using this with Create React App. When I do `npm run build` it throws this error:
`SyntaxError: Unexpected token: name (RSH) [./~/apac/lib/request-signature-helper.js:5,0]`

**Comment by dmcquay** [comment]
I do not support usage of this model in the browser. Doing so is a security vulnerability since it will expose your amazon secret key. Nevertheless, if you want to try to do it anyway, the error you're getting seems to be class syntax. Maybe the default Babel config doesn't support the syntax being used?
